# Generated by Django 6.0.5 on 2026-05-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='needed_time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
